### ISSUE TITLE
Support send and forget messages?

### ISSUE THREAD

**Issue by ergl** [lpgauth/shackle#114]
Hi! I see that currently shackle expects all messages to fit into a request-response pattern, would it be possible to add a way to send a message through the client without expecting a reply?

Use-case: you want to send a message to a server, but the server won't send a response. Currently the way to get around the request-response limitation is to implement `handle_timeout/2` with a dummy return (for example):

```erlang
%% at shackle_client
%% won't care about the reply
handle_request({cast, Msg}, State) -> {ok, 0, Msg, State}.

handle_timeout(0, State) -> {ok, {0, ok}, State}.

%% ...

%% at call site
ok = shackle:call(pool, {cast, <<"don't care">>}, 0).
```

My idea would be to let `Client:handle_request/2` return `{ok, Data :: iodata(), State :: term()}`, signalling that it won't expect a reply for that message. This would avoid storing the a dummy request identifier, and bypass the timeout mechanism.

(I think this what #72 tried to address)

**Comment by lpgauth** [comment]
Hi @ergl,
I suppose this is to fire UDP packets?

It shouldn't be hard to add, let me just think of the best way to pass that option. `pid = undefined` already has a meaning and if I use that I will break backward compatibility.

**Comment by ergl** [comment]
>  I suppose this is to fire UDP packets?

Not necessarily, in my case this is over TCP, where the server doesn't reply to the client, but I could see the how this could help with UDP, too.

> It shouldn't be hard to add, let me just think of the best way to pass that option.

Sure! It would be good to the let client module know about this too, since we can avoid generating a new request identifier if we know no reply will come. (that's what I suggested by letting the `handle_request/2` function return just `{ok, Data :: iodata(), State :: term()}`).

**Comment by lpgauth** [comment]
Sorry for taking a while on this, I've been swamped. After playing with a couple different options, I think the easiest is actually to expect no reply if you return `undefined` as the request identifier.

https://github.com/lpgauth/shackle/compare/feature/send-no-return?expand=1

Does that work for you?

**Comment by ergl** [comment]
Hi! Don't worry, we're all busy :^) I appreciate you putting time into this, and I think your change looks good. Do you think it's necessary to add a `reply(Id, ok, Cast)` in the path where the driver returns `undefined`? If a client uses `call`, or for some reason decides to call `receive_response/2`, I think we should immediately return `ok`.

If you're swamped, I could put a pull request together, and you can review it when you have the time. I've done some changes in a local fork, so I'm not blocked on this issue, so don't worry about getting this done fast!

**Comment by lpgauth** [comment]
Ah, I kind of just assumed that if you don't expect a response, you're using cast. That's actually not a bad idea.

**Comment by lpgauth** [comment]
Alright, so if you don't expect a response just return undefined for the request_id() and you will automatically get an `ok` reply. It's merge and tagged as `0.6.10`.

**Comment by ergl** [comment]
Great, thanks!
