### ISSUE TITLE
ARM build fails

### ISSUE THREAD

**Issue by mzealey** [lpgauth/shackle#122]
Due to https://github.com/tokenrove/granderl/issues/13 the ARM build for this (and hence https://github.com/lpgauth/statsderl) is failing. Certainly for statsderl I don't believe that the prng code in granderl is actually needed. Is there any way to work around this at build time eg via some environment/configuration variable so that we can get some functionality working on ARM without granderl issues needing to be resolved?

**Comment by lpgauth** [comment]
@mzealey `granderl` is actually used by shackle [here](https://github.com/lpgauth/shackle/blob/master/src/shackle_utils.erl#L54).

Give me a few days and I'll get it working under ARM. I saw @tokenrove already made a patch for ARM64 support.

**Comment by lpgauth** [comment]
@mzealey it's fixed in `0.16.6`
