### ISSUE TITLE
connection closed messages are spamming the logs

### ISSUE THREAD

**Issue by silviucpp** [lpgauth/shackle#124]
Can you please remove : ?WARN(PoolName, "connection closed", []), from the code. 

There are http servers that doesnt support persistent connections and are closing your socket after each request. This is spamming the logs when using buoy. 

Silviu

**Comment by lpgauth** [comment]
Hey @silviucpp, does switching the log level to DEBUG an OK fix for you?

**Comment by silviucpp** [comment]
yes !

**Comment by lpgauth** [comment]
@silviucpp FYI, I changed the "connection closed" message to `DEBUG` level and pushed a new release of [buoy](https://github.com/lpgauth/buoy/releases/tag/0.2.3)
