### ISSUE TITLE
Publish to hex.pm

### ISSUE THREAD

**Issue by antipax** [lpgauth/shackle#23]
Hi,

Just thought I would ask if you could publish this library to hex.pm? There are a number of benefits to having the library on hex, for both Erlang and Elixir projects. Here's the documentation for rebar3, which it already seems you are using: https://hex.pm/docs/rebar3_publish

I would love to contribute by sending a pull request but I imagine this is something you'd rather have full control over. Let me know if I can help in any way!

Thanks!

**Comment by lpgauth** [comment]
Fixed in https://github.com/lpgauth/shackle/pull/25.

https://hex.pm/packages/shackle

**Comment by antipax** [comment]
Thank you very much @lpgauth! ❤️
