### ISSUE TITLE
Granderl is not currently compiling on osx

### ISSUE THREAD

**Issue by silviucpp** [lpgauth/shackle#28]
Hello,

Granderl is not cross compiling yet and is limiting the usage of your library on OSX. 
I see you recently integrated this one. Maybe you can do something to use on osx another library

Silviu

**Comment by lpgauth** [comment]
Can you show me the error? Compiles fine for me on macOS `10.11.5`.

**Comment by silviucpp** [comment]
Seems it's an issue only with rebar not with rebar3 : https://github.com/tokenrove/granderl/issues/2.

**Comment by silviucpp** [comment]
This will be fixed in https://github.com/tokenrove/granderl/issues/3

**Comment by lpgauth** [comment]
Will release a new version of `shackle` as soon as https://github.com/tokenrove/granderl/issues/3 is merged.

**Comment by lpgauth** [comment]
Released shackle 0.3.5 with `Granderl` v0.1.4 which should fix your build issues.
