### ISSUE TITLE
granderl in applications list

### ISSUE THREAD

**Issue by tsloughter** [lpgauth/shackle#41]
`granderl` isn't included in the applications list of the `.app.src` file. This will mean it won't be considered a runtime dependency by rebar3 and relx and thus not be included in any releases that rely on shackle.

So it should be added to the list before publishing a new hex package that includes it as a dependency.

**Comment by lpgauth** [comment]
Should be fixed.

**Comment by tsloughter** [comment]
The hex package still has no deps: https://hex.pm/packages/shackle/0.4.3

**Comment by lpgauth** [comment]
Ok, I upgraded `rebar3` and now it's there... this is so painful.

**Comment by tsloughter** [comment]
Sorry about that. It has been stable interface for a while now, but there was a change at one point that broke it like this. Hopefully it will not be a pain anymore going forward.

Thanks!
