### ISSUE TITLE
shackle on CentOS 6, tcp data lose

### ISSUE THREAD

**Issue by getong** [lpgauth/shackle#73]

**Comment by lpgauth** [comment]
Can you give more info?

**Comment by getong** [comment]
On  CentOS, use gcc 4.8.2 with testing-devtools-2 installed
```
[testing-devtools-2-centos-$releasever]
name=testing 2 devtools for CentOS $releasever 
baseurl=http://people.centos.org/tru/devtools-2/$releasever/$basearch/RPMS
gpgcheck=0
```
Vmware, 1 cpu, 2G memory.

**Comment by lpgauth** [comment]
Ok, but what data is lost? In what context? How can I reproduce?

**Comment by getong** [comment]
Only one process not lose data, but more than one will lose. I don't know why.
