### ISSUE TITLE
update hex package to 0.5.3

### ISSUE THREAD

**Issue by tsloughter** [lpgauth/shackle#75]
I was going to open an issue asking about a crash I've been seeing where `send_after` is passed `none` for the reconnect timeout, but then I noticed maybe it was something fixed between 0.5.1 and 0.5.3? I'll look at the diffs in a minute, but either way, could you publish the latest version to hex? Thanks!

**Comment by tsloughter** [comment]
Never mind, the `none` issue is still there, will open another issue when I track down more information.

**Comment by lpgauth** [comment]
If I remember correctly, I removed support for 'none' in 0.5. Is it something you absolutely need?

**Comment by tsloughter** [comment]
@lpgauth dammit, yea, my bad @evanmcc noticed we were in the wrong and patched it :) https://github.com/SpaceTime-IoT/vonnegut/pull/84/files
