### ISSUE TITLE
Any plan to add metrics for the pools ?

### ISSUE THREAD

**Issue by silviucpp** [lpgauth/shackle#93]
Hello do you have any plan to add metrics for the pools ? Like:

- connections_up (counter)
- total_requests (counter)
- finished_requests (counter)
- running_requests (counter)
- response_time (histogram)

Kind regards,
Silviu

**Comment by lpgauth** [comment]
WIP https://github.com/lpgauth/shackle/pull/101

**Comment by lpgauth** [comment]
merged.
